- name: Pokemon
  request:
    method: GET
    endpoints:
      - /pokemon
    serveEndpoint: /api/v2/pokemon
  response:
    code: 200
    headers:
      content-type: application/json
    serveBody:
      {
        "count": 1281,
        "next": "https://pokeapi.co/api/v2/pokemon/?offset=20&limit=20",
        "previous": null,
        "results": [
          {
            "name": "bulbasaur",
            "url": "https://pokeapi.co/api/v2/pokemon/1/"
          }
        ]
      }

- name: Bulbasaur
  request:
    method: GET
    endpoints:
      - /pokemon/bulbasaur
    serveEndpoint: /api/v2/pokemon
  response:
    code: 200
    headers:
      content-type: application/json
    serveBody:
      {
        "base_experience": 64,
        "height": 7,
        "id": 1,
        "name": "bulbasaur",
        "order": 1,
        "types": [
          {
            "slot": 1,
            "type": {
              "name": "grass",
              "url": "https://pokeapi.co/api/v2/type/12/"
            }
          },
          {
            "slot": 2,
            "type": {
              "name": "poison",
              "url": "https://pokeapi.co/api/v2/type/4/"
            }
          }
        ],
        "weight": 69
      }
